# ================================
CXX = g++
CXXFLAGS = -Wall -pedantic -g
OBJECTS = main.o 
# ================================

main: $(OBJECTS)
	$(CXX) -o main $(CXXFLAGS) $(OBJECTS)

main.o: 

.PHONY: clean
clean:
	rm main $(OBJECTS)